_wandb:
    value:
        cli_version: 0.22.1
        e:
            uxr1z21ic3r5dh58qtm94k7jvua4kwiw:
                codePath: cmapss_fact_table_creation_progress_10_15.ipynb
                codePathLocal: cmapss_fact_table_creation_progress_10_15.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "499963174912"
                        used: "453340094464"
                email: djhavera@yahoo.com
                executable: /Users/davidhavera/CS598_FDC/.venv/bin/python
                host: Davids-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-15.6.1-x86_64-i386-64bit-Mach-O
                program: /Users/davidhavera/CS598_FDC/cmapss_fact_table_creation_progress_10_15.ipynb
                python: CPython 3.13.1
                root: /Users/davidhavera/CS598_FDC
                startedAt: "2025-10-27T15:18:43.072742Z"
                writerId: uxr1z21ic3r5dh58qtm94k7jvua4kwiw
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.1
            "5": 0.22.1
            "8":
                - 1
            "10":
                - 21
            "12": 0.22.1
            "13": darwin-x86_64
datasets:
    value:
        - FD001
        - FD002
        - FD003
        - FD004
module:
    value: M7 - What is Data?
num_datasets:
    value: 4
train_test_split:
    value: original
