_wandb:
    value:
        cli_version: 0.22.1
        e:
            26jnipaghta1o82zhkv5kjzpdr15blou:
                codePath: cmapss_fact_table_creation_progress_10_15.ipynb
                codePathLocal: cmapss_fact_table_creation_progress_10_15.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "499963174912"
                        used: "448386424832"
                email: djhavera@yahoo.com
                executable: /Users/davidhavera/CS598_FDC/.venv/bin/python
                host: Davids-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-15.6.1-x86_64-i386-64bit-Mach-O
                program: /Users/davidhavera/CS598_FDC/cmapss_fact_table_creation_progress_10_15.ipynb
                python: CPython 3.13.1
                root: /Users/davidhavera/CS598_FDC
                startedAt: "2025-10-24T16:28:31.164396Z"
                writerId: 26jnipaghta1o82zhkv5kjzpdr15blou
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.1
            "5": 0.22.1
            "8":
                - 1
            "10":
                - 21
            "12": 0.22.1
            "13": darwin-x86_64
input_dataset:
    value: fact_table_sensor_deduplicated
module:
    value: M12 - Reproducibility & Transparency
normalization_method:
    value: z-score
num_derived_features:
    value: 4
num_sensors:
    value: 21
output_dataset:
    value: fact_table_transformed
pressure_index_sensors:
    value:
        - sensor_7
        - sensor_8
        - sensor_9
scaler_type:
    value: StandardScaler
thermal_index_sensors:
    value:
        - sensor_2
        - sensor_3
        - sensor_4
transformation_phases:
    value:
        - syntactic_normalization
        - semantic_feature_engineering
